name: Categorize rush projects by deploy configurations
description: Categorizes rush projects by deploy target based on configurations. Curently respects rush `shouldPublish` flag and package.json `deployCategory` field.
inputs:
  rushProjects:
    description: Array of rush projects to be categorized.
    required: true
outputs:
  categories:
    description: Categorized project directories.
runs:
  using: node12
  main: dist/index.js
