name: Categorize rush projects by deploy configurations
description: Categorizes rush projects by deploy target based on configurations. Curently respects rush `shouldPublish` flag and package.json `deployCategory` field.
inputs:
  rushJsonPath:
    description: Path to a valid rush json file.
    required: false
    default: './rush.json'
outputs:
  # This action sets dynamic outputs according to deployCategory value in package.json
  # For example all packages with category "k8s" will be grouped in array under outputs.k8s
  npm-package:
    description: List of packages to be published to npm.
runs:
  using: node12
  main: dist/index.js
